# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150906080247 on 2015-09-06 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importobjects',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_objects', to='pupa.RunPlan'),
        ),
        migrations.AlterField(
            model_name='runplan',
            name='jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='scrapeobjects',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_objects', to='pupa.ScrapeReport'),
        ),
        migrations.AlterField(
            model_name='scrapereport',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapers', to='pupa.RunPlan'),
        ),
    ]
