# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-18 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pupa', '0002_auto_20150906_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='runplan',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runplan',
            name='exception',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='runplan',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0, 0, 0, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runplan',
            name='traceback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
